backend:
  name: test-repo
media_folder: static/assets
public_folder: /assets
collections:
  - name: galleryImage
    label: Image
    folder: galleryImage
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "gallery-image",
        }
      - { label: "Image", name: "image", widget: image }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Caption", name: "caption", widget: "text" }
      - { label: "Alt", name: "alt", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - {
          label: "Collection",
          name: "collectionGallery",
          widget: "relation",
          collection: "galleryCollection",
          value_field: "{{slug}}",
          search_fields: ["title"],
          display_fields: ["title"],
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
  - name: galleryCollection
    label: Collection
    folder: gallerycollection
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "gallery-collection",
        }
      - { label: "Hero Image", name: "heroImage", widget: image }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Caption", name: "caption", widget: "text" }
      - { label: "Alt", name: "alt", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Front Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: "Image", name: "image", widget: image }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Caption", name: "caption", widget: "text" }
          - { label: "Alt", name: "alt", widget: "string" }
